test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 1940761276158757
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 1940761276158757
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
